### PR TITLE
.NET 7 and filescoped name spaces

### PR DESCRIPTION
**Pull request by NullableInt**
Experimental support for .NET 7.
Also use file scoped namespaces because I like it.

The plan is also to convert a lot of the models to `record`s in the next pull request, also because I like it.
But also because it gives us really nice syntax for working with models where all properties can be `{ get; init; }` and I look forward to adding it.
❤️ 💘 ❤️

### CODE REVIEW

**Comment by NullableInt** [comment]
@xillians I also wanna bug you with this knowledge.

**Review by asbjornu — CHANGES_REQUESTED** [review]
18399 additions, 19010 deletions
Wow!

Wow. Nice! But also, sadface – there's errors: 😞 

```
Error: /usr/share/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1047: Assets file '/home/runner/work/swedbank-pay-sdk-dotnet/swedbank-pay-sdk-dotnet/src/Samples/Sample.AspNetCore/obj/project.assets.json' doesn't have a target for 'net6.0/win-x64'. Ensure that restore has run and that you have included 'net6.0' in the TargetFrameworks for your project. You may also need to include 'win-x64' in your project's RuntimeIdentifiers. [/home/runner/work/swedbank-pay-sdk-dotnet/swedbank-pay-sdk-dotnet/src/Samples/Sample.AspNetCore/Sample.AspNetCore.csproj]
```

**Comment by NullableInt** [comment]
I hopefully will have time to fix this soon.

**Comment by zunkas** [comment]
A new version supporting version 3.1 with .net 8 and filescoped namespaces have been merged to develop.

**Pull request closed without merging**
